In [1]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Vectors operations

In [5]:
u = np.array([2,4,5,6])
2 * u 

array([ 4,  8, 10, 12])

In [6]:
v = np.array([1,0,0,2])
u + v

array([3, 4, 5, 8])

## Multiplication

### vector vector multiplication

In [15]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
    return float(result)

In [16]:
vector_vector_multiplication(u,v)

14.0

In [20]:
float (u.dot(v))

14.0

### Matrix-vector multiplication

In [22]:
U = np.array([[2,4,5,6], 
              [1,2,1,2], 
              [3,1,2,1],
             ])

In [23]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [26]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    return (result)

In [27]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [28]:
U.dot(v)

array([14,  5,  5])

### Matrix-matrix multiplication

In [29]:
V = np.array([[1,1,2], 
              [0,0.5,1],
              [0,2,1],
              [2,1,0],
             ])

In [37]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    return result
        

In [38]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [39]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity  Matrix

In [42]:
I = np.eye(3)

In [44]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [43]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Matrix inverse

In [50]:
Vs = V[[0,1,2]]

In [51]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [53]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])